# Generated by Django 3.1.4 on 2020-12-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('timeframe', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('big_goal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='goals.big_goal')),
                ('day_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='goals.day')),
            ],
        ),
        migrations.CreateModel(
            name='List_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('big_goal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='goals.big_goal')),
                ('day_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='goals.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='goals.user'),
        ),
        migrations.AddField(
            model_name='big_goal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_goals', to='goals.user'),
        ),
    ]
