# Generated by Django 3.1.4 on 2020-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
